[package]
name = "rust-lockfree"
version = "0.1.0"

[dependencies]
clap = "2.33.0"
spin = "0.5.2"
crossbeam-queue = "0.2.1"
crossbeam-epoch = "0.8.2"
lockfree = "0.5.1"
stderrlog = "0.4.2"
log = "0.4.8"
